# Usar la imagen oficial de PostgreSQL como base
FROM postgres:13

# Establecer las variables de entorno para PostgreSQL
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

# Exponer el puerto 5432 para PostgreSQL
EXPOSE 5432

# Comando para iniciar PostgreSQL
CMD ["postgres"]
